<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles/habitacion.css">
    
</head>

<?php foreach ($habitaciones as $habitacion) { ?>
    <?php if (!$habitacion->ocupada) { ?>
        
        <ul>
            <li class="habitaciones_libres">
                <h1>El numero de habitacion es <?= $habitacion->nro_habitacion?></h1>
                <p>Descripcion: <?= $habitacion->descripcion?></p>
            
            </li>
        </ul>
    <?php }else{?>
        <ul>
            <li>
                <h1>El numero de habitacion es <?= $habitacion->nro_habitacion?></h1>
                <p>Descripcion: <?= $habitacion->descripcion?></p>
            
            </li>
        </ul>
    <?php }?>
<?php }?>
